- .github/workflows/semantic-pull-request.yml
> Enforce semantic PR titles

- .github/workflows/ci.yml
- .github/workflows/goreleaser.yml
Do not trigger on pull requests
> fix: goreleaser ci

- Makefile
- reaction/action/webhook/webhook_test.go
- ui/src/components/sidebar/UserDropDown.vue
Redirect on outdated user sessions
> fix: redirect to login

- Makefile
- app/app.go
- app/flags.go
- app/flags_test.go
- ui/src/assets/main.css
- ui/src/components/common/UserSelectList.vue
- ui/src/components/form/JSONSchemaFormFields.vue
- ui/src/components/form/MultiSelect.vue
- ui/src/components/reaction/ReactionDisplay.vue
- ui/src/components/reaction/ReactionForm.vue
- ui/src/components/reaction/ReactionList.vue
- ui/src/components/ticket/TicketList.vue
- ui/src/components/ticket/TicketNewDialog.vue
- ui/src/components/ticket/file/TicketFiles.vue
- ui/src/components/ticket/timeline/TicketTimelineItem.vue
- ui/src/views/LoginView.vue
- ui/src/views/ReactionView.vue
Disable files and reactions in demos
> feat: demo flags

- ui/src/components/common/CatalystLogo.vue
- ui/src/components/layout/SideBar.vue
- ui/src/router/index.ts
- ui/src/views/LoginView.vue
- ui/src/views/PasswordResetView.vue
> feat: reset password

- ui/src/components/form/GrowTextarea.vue
- ui/src/components/form/MultiSelect.vue
Fix MultiSelect state handling
> fix: multi select state handling

- Makefile
- go.mod
- go.sum
- reaction/trigger/hook/hook.go
Fix an issue where events are only sent to one registerd hook.
> fix: multiple hooks

- .goreleaser.yaml
- docker/Dockerfile
- docker/goreleaser.Dockerfile
Add docker files and goreleaser docker image builds
> feat: docker files

- .goreleaser.yaml
- Makefile
- app/routes.go
- docker/Dockerfile
- docker/goreleaser.Dockerfile
Add docker healthcheck and add python
> feat: docker healthcheck

- app/flags.go
> fix: set-app-url

- migrations/9_reactions_update.go
- migrations/migrations.go
- reaction/schedule/schedule.go
- reaction/trigger.go
- ui/src/components/reaction/ReactionForm.vue
- ui/src/components/reaction/ReactionList.vue
- ui/src/components/reaction/TriggerScheduleFormFields.vue
- ui/src/components/reaction/TriggerWebhookFormFields.vue
> feat: scheduler

- fakedata/records.go
Add example for scheduler triggered reaction.
> feat: scheduler example

- ui/src/components/dashboard/OpenTickets.vue
Fix relative day display in the Dashboard
> fix: relative day display

- ui/src/components/form/JSONSchemaFormFields.vue
Add integer custom fields.
Fixes #1122
> feat: support integer custom field

- .github/workflows/goreleaser.yml
> fix: release CI

- docker/entrypoint.sh
- main.go
> fix: recreate http flag

- .github/workflows/goreleaser.yml
- .goreleaser.yaml
Adapt goreleaser for cross compilation
> fix: adapt goreleaser for cross compilation

- .goreleaser.yaml
> fix: release docker ids

- .goreleaser.yaml
> fix: rename binary

- ui/src/components/form/JSONSchemaFormFields.vue
- ui/src/components/group/GroupForm.vue
- ui/src/components/group/GroupSelectDialog.vue
- ui/src/components/reaction/ActionPythonFormFields.vue
- ui/src/components/reaction/ActionWebhookFormFields.vue
- ui/src/components/reaction/ReactionForm.vue
- ui/src/components/reaction/TriggerHookFormFields.vue
- ui/src/components/reaction/TriggerScheduleFormFields.vue
- ui/src/components/reaction/TriggerWebhookFormFields.vue
- ui/src/components/settings/SettingsForm.vue
- ui/src/components/ticket/TicketNewDialog.vue
- ui/src/components/ticket/link/LinkAddDialog.vue
- ui/src/components/type/TypeForm.vue
- ui/src/components/user/UserForm.vue
- ui/src/components/user/UserPasswordForm.vue
- ui/src/components/user/UserSelectDialog.vue
> fix: text alignment
